{
    'name': 'Sports Association',
    'summary': 'Manage sports association, teams and events.',
    'version': '17.0.1.0.0',
    'category': 'Sports',
    'author': 'Yuniel Villalón',
    'license': 'AGPL-3',
    'application': False,
    'installable': True,
    'depends': ['base'],
    'data': [
            'data/sport_licence_data.xml',
            'security/groups.xml',
            'security/ir.model.access.csv',
            'views/sport_issue_views.xml',
            'views/sport_clinic_views.xml',
            'views/sport_issue_tag_views.xml',
            'views/sport_menuitems.xml',
],
}
